// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Data.Models.Strava.DetailedActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AthleteCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageWatts")
                        .HasColumnType("REAL");

                    b.Property<float?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Commute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("DeviceWatts")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ElevHigh")
                        .HasColumnType("REAL");

                    b.Property<float?>("ElevLow")
                        .HasColumnType("REAL");

                    b.Property<string>("EmbedToken")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("EndLatlng")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Flagged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GearId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasKudoed")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Kilojoules")
                        .HasColumnType("REAL");

                    b.Property<int?>("KudosCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Manual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<float?>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("MaxWatts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Polyline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("StartLatlng")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("TotalElevationGain")
                        .HasColumnType("REAL");

                    b.Property<int?>("TotalPhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Trainer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UploadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeightedAverageWatts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkoutType")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("_Private")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("MapId")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedSegmentEffort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageCadence")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageHeartrate")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageWatts")
                        .HasColumnType("REAL");

                    b.Property<bool?>("DeviceWatts")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsKom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KomRank")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MaxHeartrate")
                        .HasColumnType("REAL");

                    b.Property<int?>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrRank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("SegmentId");

                    b.ToTable("SegmentEfforts");
                });

            modelBuilder.Entity("Data.Models.Strava.Lap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageCadence")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<long>("DetailedActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LapIndex")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaceZone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Split")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartIndex")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("TotalElevationGain")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DetailedActivityId");

                    b.ToTable("Lap");
                });

            modelBuilder.Entity("Data.Models.Strava.MetaActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MetaActivity");
                });

            modelBuilder.Entity("Data.Models.Strava.MetaAthlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MetaAthletes");
                });

            modelBuilder.Entity("Data.Models.Strava.PolylineMap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Polyline")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryPolyline")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PolylineMaps");
                });

            modelBuilder.Entity("Data.Models.StravaUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessTokenExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StravaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Strava.NET.Model.SummarySegment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AthletePrEffortId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageGrade")
                        .HasColumnType("REAL");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClimbCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<float?>("ElevationHigh")
                        .HasColumnType("REAL");

                    b.Property<float?>("ElevationLow")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("EndLatlng")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("MaximumGrade")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("StartLatlng")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("_Private")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AthletePrEffortId");

                    b.ToTable("SummarySegment");
                });

            modelBuilder.Entity("Strava.NET.Model.SummarySegmentEffort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsKom")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SummarySegmentEffort");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedActivity", b =>
                {
                    b.HasOne("Data.Models.Strava.MetaAthlete", "Athlete")
                        .WithMany("Activities")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Strava.PolylineMap", "Map")
                        .WithOne("Activity")
                        .HasForeignKey("Data.Models.Strava.DetailedActivity", "MapId");

                    b.Navigation("Athlete");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedSegmentEffort", b =>
                {
                    b.HasOne("Data.Models.Strava.DetailedActivity", "DetailedActivity")
                        .WithMany("SegmentEfforts")
                        .HasForeignKey("ActivityId");

                    b.HasOne("Strava.NET.Model.SummarySegment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailedActivity");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Data.Models.Strava.Lap", b =>
                {
                    b.HasOne("Data.Models.Strava.DetailedActivity", "DetailedActivity")
                        .WithMany("Laps")
                        .HasForeignKey("DetailedActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailedActivity");
                });

            modelBuilder.Entity("Strava.NET.Model.SummarySegment", b =>
                {
                    b.HasOne("Strava.NET.Model.SummarySegmentEffort", "AthletePrEffort")
                        .WithMany()
                        .HasForeignKey("AthletePrEffortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthletePrEffort");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedActivity", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("SegmentEfforts");
                });

            modelBuilder.Entity("Data.Models.Strava.MetaAthlete", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Data.Models.Strava.PolylineMap", b =>
                {
                    b.Navigation("Activity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
