// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Data.Models.Strava.AltitudeStream", b =>
                {
                    b.Property<int>("AltitudeStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("AltitudeStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("AltitudeStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.CadenceStream", b =>
                {
                    b.Property<int>("CadenceStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("CadenceStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("CadenceStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AthleteCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageWatts")
                        .HasColumnType("REAL");

                    b.Property<float?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Commute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("DeviceWatts")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ElevHigh")
                        .HasColumnType("REAL");

                    b.Property<float?>("ElevLow")
                        .HasColumnType("REAL");

                    b.Property<string>("EmbedToken")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("EndLatlng")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Flagged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GearId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasKudoed")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Kilojoules")
                        .HasColumnType("REAL");

                    b.Property<int?>("KudosCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Manual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<float?>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("MaxWatts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Polyline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("StartLatlng")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("TotalElevationGain")
                        .HasColumnType("REAL");

                    b.Property<int?>("TotalPhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Trainer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UploadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeightedAverageWatts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkoutType")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("_Private")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("MapId")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedSegmentEffort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageCadence")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageHeartrate")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageWatts")
                        .HasColumnType("REAL");

                    b.Property<bool?>("DeviceWatts")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsKom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KomRank")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MaxHeartrate")
                        .HasColumnType("REAL");

                    b.Property<int?>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrRank")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("SegmentId");

                    b.ToTable("SegmentEfforts");
                });

            modelBuilder.Entity("Data.Models.Strava.DistanceStream", b =>
                {
                    b.Property<int>("DistanceStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("DistanceStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("DistanceStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.HeartrateStream", b =>
                {
                    b.Property<int>("HeartrateStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeartrateStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("HeartrateStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.Lap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageCadence")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<long>("DetailedActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LapIndex")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaceZone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Split")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartIndex")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("TotalElevationGain")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DetailedActivityId");

                    b.ToTable("Lap");
                });

            modelBuilder.Entity("Data.Models.Strava.LatLngStream", b =>
                {
                    b.Property<int>("LatLngStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("LatLngStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("LatLngStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.MetaActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MetaActivity");
                });

            modelBuilder.Entity("Data.Models.Strava.MetaAthlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MetaAthletes");
                });

            modelBuilder.Entity("Data.Models.Strava.MovingStream", b =>
                {
                    b.Property<int>("MovingStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovingStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("MovingStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.PolylineMap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Polyline")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryPolyline")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PolylineMaps");
                });

            modelBuilder.Entity("Data.Models.Strava.PowerStream", b =>
                {
                    b.Property<int>("PowerStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("PowerStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("PowerStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.SmoothGradeStream", b =>
                {
                    b.Property<int>("SmoothGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("SmoothGradeId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("SmoothGradeStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.SmoothVelocityStream", b =>
                {
                    b.Property<int>("SmoothVelocityStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("SmoothVelocityStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("SmoothVelocityStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.StreamSet", b =>
                {
                    b.Property<int>("StreamSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StreamSetId");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("Data.Models.Strava.SummarySegment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityType")
                        .HasColumnType("TEXT");

                    b.Property<float?>("AverageGrade")
                        .HasColumnType("REAL");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClimbCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<float?>("ElevationHigh")
                        .HasColumnType("REAL");

                    b.Property<float?>("ElevationLow")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("EndLatlng")
                        .HasColumnType("TEXT");

                    b.Property<float?>("MaximumGrade")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("StartLatlng")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("_Private")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("Data.Models.Strava.TemperatureStream", b =>
                {
                    b.Property<int>("TemperatureStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("TemperatureStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("TemperatureStreams");
                });

            modelBuilder.Entity("Data.Models.Strava.TimeStream", b =>
                {
                    b.Property<int>("TimeStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StreamSetId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeStreamId");

                    b.HasIndex("StreamSetId")
                        .IsUnique();

                    b.HasIndex("StreamSetId1")
                        .IsUnique();

                    b.ToTable("TimeStreams");
                });

            modelBuilder.Entity("Data.Models.StravaUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessTokenExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StravaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.Models.Strava.AltitudeStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.AltitudeStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Altitude")
                        .HasForeignKey("Data.Models.Strava.AltitudeStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.CadenceStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.CadenceStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Cadence")
                        .HasForeignKey("Data.Models.Strava.CadenceStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedActivity", b =>
                {
                    b.HasOne("Data.Models.Strava.MetaAthlete", "Athlete")
                        .WithMany("Activities")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Strava.PolylineMap", "Map")
                        .WithOne("Activity")
                        .HasForeignKey("Data.Models.Strava.DetailedActivity", "MapId");

                    b.Navigation("Athlete");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedSegmentEffort", b =>
                {
                    b.HasOne("Data.Models.Strava.DetailedActivity", "DetailedActivity")
                        .WithMany("SegmentEfforts")
                        .HasForeignKey("ActivityId");

                    b.HasOne("Data.Models.Strava.SummarySegment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId");

                    b.Navigation("DetailedActivity");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Data.Models.Strava.DistanceStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.DistanceStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Distance")
                        .HasForeignKey("Data.Models.Strava.DistanceStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.HeartrateStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.HeartrateStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Heartrate")
                        .HasForeignKey("Data.Models.Strava.HeartrateStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.Lap", b =>
                {
                    b.HasOne("Data.Models.Strava.DetailedActivity", "DetailedActivity")
                        .WithMany("Laps")
                        .HasForeignKey("DetailedActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailedActivity");
                });

            modelBuilder.Entity("Data.Models.Strava.LatLngStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.LatLngStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Latlng")
                        .HasForeignKey("Data.Models.Strava.LatLngStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.MovingStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.MovingStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Moving")
                        .HasForeignKey("Data.Models.Strava.MovingStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.PowerStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.PowerStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Watts")
                        .HasForeignKey("Data.Models.Strava.PowerStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.SmoothGradeStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.SmoothGradeStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("GradeSmooth")
                        .HasForeignKey("Data.Models.Strava.SmoothGradeStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.SmoothVelocityStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.SmoothVelocityStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("VelocitySmooth")
                        .HasForeignKey("Data.Models.Strava.SmoothVelocityStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.StreamSet", b =>
                {
                    b.HasOne("Data.Models.Strava.DetailedActivity", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.StreamSet", "ActivityId");
                });

            modelBuilder.Entity("Data.Models.Strava.TemperatureStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.TemperatureStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Temp")
                        .HasForeignKey("Data.Models.Strava.TemperatureStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.TimeStream", b =>
                {
                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne()
                        .HasForeignKey("Data.Models.Strava.TimeStream", "StreamSetId");

                    b.HasOne("Data.Models.Strava.StreamSet", null)
                        .WithOne("Time")
                        .HasForeignKey("Data.Models.Strava.TimeStream", "StreamSetId1");
                });

            modelBuilder.Entity("Data.Models.Strava.DetailedActivity", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("SegmentEfforts");
                });

            modelBuilder.Entity("Data.Models.Strava.MetaAthlete", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Data.Models.Strava.PolylineMap", b =>
                {
                    b.Navigation("Activity")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Strava.StreamSet", b =>
                {
                    b.Navigation("Altitude")
                        .IsRequired();

                    b.Navigation("Cadence")
                        .IsRequired();

                    b.Navigation("Distance")
                        .IsRequired();

                    b.Navigation("GradeSmooth")
                        .IsRequired();

                    b.Navigation("Heartrate")
                        .IsRequired();

                    b.Navigation("Latlng")
                        .IsRequired();

                    b.Navigation("Moving")
                        .IsRequired();

                    b.Navigation("Temp")
                        .IsRequired();

                    b.Navigation("Time")
                        .IsRequired();

                    b.Navigation("VelocitySmooth")
                        .IsRequired();

                    b.Navigation("Watts")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
